version: '3.8'

services:
  db:
    image: postgres:12.2-alpine
    ports:
      - "5332:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
  pgadmin:
        image: dpage/pgadmin4
        environment:
          - PGADMIN_DEFAULT_EMAIL=ciochina7@gmail.com
          - PGADMIN_DEFAULT_PASSWORD=password
        ports:
            - "5050:80"

